Cadencesnwg
LSSTDESC/SNData pull request #9
Opened 2017-03-06 22:06 UTC by lgalbany

Now LightCurve gives an error when it is created instead than when it is used, when input does not exist.

I modified a bit Demo_LightCurve.ipynb to make it independent of AnalyzeSN

2017-03-08 19:51 UTC, rbiswas4 requested changes
Removes the dependency on analyzeSN and moves some functionality in `lightcurve` to warn user if the input does not have correct columns at the beginning.

Things to do :
- remove `cov_utils.py`, squash and force push to master

Then it will be good to merge.

2017-03-10 02:38 UTC, lgalbany commented
cov_utils.py deleted

2017-03-10 02:43 UTC, rbiswas4 approved these changes

2017-03-10 02:44 UTC, lgalbany commented
I also updated the example notebook!

2017-03-10 02:45 UTC, merged